classDiagram
direction TB
    class Vault {
        <<Entity>>
	    +vaultId: xs:string
    }

    class Organization {
        <<Entity>>/Users/henarmartinsantos/Desktop/FAQIR/PACSOI/dataModel/datamodel/src/datamodel/schema/questionnaire/questionnaire_classes.yaml
	    +organizationId: xs:string/Users/henarmartinsantos/Desktop/FAQIR/PACSOI/dataModel/datamodel/src/data/examples/invalid/simple_questionnaire/Answer-01-hours_slept-01.yaml
        +organizationLabel: xs:string
        +organizationType: OrganizationType
    }

    class Procedure {
	    +procedureId: xs:string
        +procedureLabel: xs:string
        +procedureDescription: xs:string
    }

    class QuestionnaireResponse {
        <<Entity>>
	    +id questionnaireResponseId : string
	    +questionnaireResponseStatus : ResponseStatus
	    +questionnaireResponseTimeStamp : datetime
        +questionnaireResponseLastUpdated : datetime
    }

    class Questionnaire {
        <<Entity>>
	    +id questionnaireId: string
	    +questionnaireLabel : string
	    +questionnaireProvider : string (recommended)
	    +questionnaireStatus : QuestionnaireStatus 
        +questionnaireVersion : string
        +questionnaireLastUpdated : datetime
    }

    class OrderedSection {
	    +id OrderedSectionId : string
	    +sectionOrder : integer
    }
    
    class Section {
        <<Entity>>
	    +id sectionId : string
	    +rdfs:label sectionLabel : string
    }
    
    class ScoreDefinition {
        <<Entity>>
	    +id scoreDefinitionId : string
	    +rdfs:label scoreLabel : string
        +scoreFormula : float
        +scoreDescription : string
    }

    class ScoreParameter {
        +id scoreParameterId : string
        +rdfs:label scoreParameterLabel : string
        +scoreParameterType : ParameterType
    }

    class ScoreValue {
        +id scoreValueId : string
        +scoreValue : ValueNumerical
        +scoreValueTimeStamp : datetime
        +scoreStatus : ScoreStatus
    }

    class OrderedQuestion {
	    +id OrderedQuestionId : string
	    +questionOrder : integer
    }

    class Question {
        <<Entity>>
	  +id questionId : string
	  +questionLabel : string
      +questionRequired : bool
	  +questionType : QuestionType
      +questionNumericalParams : NumericalParams (if questionType=decimal/numberInterval)
      +questionIntervalParams : IntervalParams (if questionType=numberInterval)
      +questionCodingParams : ValueCoding (if questionType=choice/openChoice)
    }

    class Answer {
        <<Entity>>
	  +id answerId : string
      +answerTimeStamp: datetime
      +isEmptyAnswer : bool 
	  +questionType : QuestionType
      +answerValueNumerical : ValueNumerical (if questionType=decimal/numberInterval)
      +answerValueString : ValueString array (if questionType=choice/openChoice/text)
      +answerValueDateTime : ValueDateTime (if questionType=dateTime)
    }

    class UnitOfMeasure {
        <<enumeration>>
	  kg
      g
      lb
      cm
      m
      h
      min
    }

    class OrganizationType {
        <<enumeration>>
        hospital
        government
        professional
        research
    }

    class QuestionType {
        <<enumeration>>
	    choice
      openChoice
      numberInterval
      decimal
      dateTime
      text
    }

    class ParameterType {
        <<enumeration>>
      decimal
      dateTime
    }

    class QuestionnaireStatus {
        <<enumeration>>
        draft
        active
        retired
        unknown
    }

    class QuestionnaireResponseStatus {
        <<enumeration>>
        in_progress
        completed
        amended
        entered_in_error
        stopped
        
    }

    class ValueString {
        <<Value>>
	    +stringValue : string
    }

    class ValueCoding {
        <<Value>>
	    +code: string
	    +display: string
    }

    class ValueDateTime {
        <<Value>>
	    +dateTimeValue : dateTime
    }

    class ValueNumerical {
        <<Value>>
	    +numericalValue : decimal
    }

    class NumericalParams {
	    +numericalUnit : UnitOfMeasure
	    +numericalPrecision : integer
    }

    class IntervalParams {
	    +minValue: float
	    +minLabel: string
	    +maxValue: float
	    +maxLabel: string
    }

    note for ValueCoding "For questionType=openChoice, the last ValueCoding must be: {valueCoding: {'code': '-1', 'display': 'Other'}}"

    Vault --> "0..*" QuestionnaireResponse : "hasQuestionnaireResponse"
    Vault --> "1" Organization : "vaultManagedByOrg"
    QuestionnaireResponse --> "1" Vault : "questionnaireResponseBySubject"
    QuestionnaireResponse --> "1" Questionnaire : "responseToQuestionnaire"
    QuestionnaireResponse "1" --> "1..*" Answer : "responseHasAnswer"
    QuestionnaireResponse --> "0..*" ScoreValue : "questionnaireResponseHasDerivedScoreValue"
    Organization --> "0..*" Vault : "organizationManagesVault"
    Organization --> "0..*" Procedure : "organizationPerformesProcedure"
    Organization --> "0..*" Questionnaire : "organizationAuthorsQuestionnaire"
    Organization --> "0..*" Section : "organizationAuthorsSection"
    Organization --> "0..*" Question : "organizationAuthorsQuestion"
    Organization --> "0..*" ScoreDefinition : "organizationAuthorsScoreDefinition"
    Procedure --> "0..*" Organization : "procedurerformedByOrganization"
    Procedure --> "0..*" Questionnaire : "procedureHasQuestionnaire"
    Questionnaire --> "0..*" QuestionnaireResponse : "questionnaireHasResponse"
    Questionnaire --> "0..1" Organization : "questionnaireAuthoredByOrg"
    Questionnaire --> "0..*" OrderedSection : "questionnaireHasOrderedSection"
    Questionnaire --> "0..*" OrderedQuestion : "questionnaireHasOrderedQuestion"
    Questionnaire --> "0..*" Procedure : "questionnairePartOfProcedure"
    Questionnaire --> "0..*" ScoreDefinition : "questionnaireHasDerivedScoreDefinition"
    OrderedSection --> "1" Section : "orderedSectionHasSection"
    Section --> "0..1" Organization : "sectionAuthoredByOrg"
    Section --> "0..*" OrderedSection : "sectionHasOrderedSection" 
    Section --> "0..*" OrderedSection : "sectionInOrderedSection" 
    Section --> "0..*" OrderedQuestion : "sectionHasOrderedQuestion"
    Section --> "0..*" ScoreDefinition : "sectionHasDerivedScoreDefinition"
    OrderedQuestion --> "1" Question : "orderedQuestionHasQuestion"
    Question --> "0..*" OrderedQuestion : "questionInOrderedQuestion"
    Question --> "0..*" Answer : "questionHasAnswer"
    Question --> "0..*" Organization : "questionAuthoredByOrg"
    Question --> "0..*" ScoreDefinition : "questionUsedInScoreDefinition"
    Answer --> "1" QuestionnaireResponse : "answerInResponse"
    Answer --> "1" Question : "answerToQuestion"
    Answer --> "0..*" ScoreValue : "answerUsedInScoreValue"
    ScoreDefinition --> "0..*" Questionnaire : "scoreDefinitionDerivedFromQuestionnaire"
    ScoreDefinition --> "0..*" Section : "scoreDefinitionDerivedFromSection"
    ScoreDefinition --> "1..*" Question : "scoreDefinitionUsesQuestion"
    ScoreDefinition --> "0..*" ScoreValue : "scoreDefinitionHasScoreValue"
    ScoreDefinition --> "0..*" Organization : "scoreDefinitionAuthoredByOrg"
    ScoreValue --> "1" ScoreDefinition : "scoreValueBasedOnDefinition"
    ScoreValue --> "1..*" QuestionnaireResponse : "scoreValueDerivedFromQuestionnaireResponse"
    ScoreValue --> "1..*" Answer : "scoreValueUsesAnswers"