# metamodel_version: 1.7.0
enum MassUnit
  {
    kg
  }

enum OrganizationType
  {
    hospital
    government
    professional
    research
    serviceProvider
  }

enum QuestionnaireResponseStatus
  {
    in_progress
    completed
    amended
    entered_in_error
    stopped
  }

enum QuestionnaireStatus
  {
    draft
    active
    retired
    unknown
  }

enum QuestionType
  {
    choice
    openChoice
    numberInterval
    decimal
    dateTime
    text
  }

enum ScoreParameterType
  {
    numerical
    dateTime
  }

enum ScoreType
  {
    numerical_continuous
    numerical_integer
    numerical_percentage
    numerical_z_score
    numerical_t_score
    categorical
  }

enum ScoreValueStatus
  {
    valid
    incomplete
    estimated
    warning
    error
    pending
    amended
  }

enum UnitOfMeasure
  {
    kg
    g
    lb
    cm
    m
    h
    min
  }

enum WeightType
  {
    BODY_WEIGHT_MEASURED
    BODY_WEIGHT_STATED
  }

type Answer
  {
    answerInQuestionnaireResponse: QuestionnaireResponse!
    answerToQuestion: Question!
    questionType: QuestionType!
    questionMultivaluedAnswer: Boolean
    answerId: Uriorcurie!
    answerValueNumerical: ValueNumerical
    answerValueString: [ValueString]
    answerValueDateTime: ValueDateTime
    answerIsEmpty: Boolean
    answerTimeStamp: Datetime!
  }

type FullName
  {
    firstName: String
    middleName: String
    familyName: String
  }

type IntervalParams
  {
    minValue: Float!
    minLabel: String
    maxValue: Float!
    maxLabel: String
  }

type Metadata
  {
    lastUpdated: Datetime!
  }

type NumericalParams
  {
    numericalUnit: UnitOfMeasure
    numericalPrecision: Integer
  }

type OrderedQuestion
  {
    orderedQuestionHasQuestion: Question!
    orderedQuestionPartOfQuestionnaire: Questionnaire
    orderedQuestionPartOfSection: Section
    orderedQuestionId: Uriorcurie!
    questionOrder: Integer!
  }

type OrderedSection
  {
    orderedSectionHasSection: Section!
    orderedSectionPartOfQuestionnaire: Questionnaire
    orderedSectionPartOfSection: Section
    orderedSectionId: Uriorcurie!
    sectionOrder: Integer!
  }

type Organization
  {
    organizationAuthorsQuestionnaire: [Questionnaire]
    organizationAuthorsSection: [Section]
    organizationAuthorsQuestion: [Question]
    organizationAuthorsScoreDefinition: [ScoreDefinition]
    organizationManagesVault: [Vault]
    organizationId: Uriorcurie!
    organizationLabel: String!
    organizationType: OrganizationType!
  }

type Procedure
  {
    procedurePerformedByOrg: [Organization]
    procedureHasQuestionnaire: [Questionnaire]
    procedureId: Uriorcurie!
    procedureLabel: String!
    procedureDescription: String
  }

type Question
  {
    questionType: QuestionType!
    questionAuthoredByOrg: [Organization]
    questionInOrderedQuestion: [OrderedQuestion]
    questionHasAnswer: [Answer]
    questionMultivaluedAnswer: Boolean
    questionUsedInScoreDefinition: [ScoreDefinition]
    questionId: Uriorcurie!
    questionTag: String!
    questionLabel: String!
    questionNumericalParams: NumericalParams
    questionCodingParams: [ValueCoding]
    questionCodingOrdinal: Boolean
    questionIntervalParams: IntervalParams
    questionRequired: Boolean
  }

type Questionnaire
  {
    questionnaireHasQuestionnaireResponse: [QuestionnaireResponse]
    questionnaireHasOrderedQuestion: [OrderedQuestion]
    questionnaireHasOrderedSection: [OrderedSection]
    questionnaireUsesScoreDefinition: [ScoreDefinition]
    questionnaireAuthoredByOrg: [Organization]
    questionnairePartOfProcedure: [Procedure]
    questionnaireId: Uriorcurie!
    questionnaireLabel: String!
    questionnaireStatus: QuestionnaireStatus!
    questionnaireVersion: String!
    questionnaireLastUpdated: Datetime!
  }

type QuestionnaireResponse
  {
    questionnaireResponseBySubject: Vault!
    questionnaireResponseToQuestionnaire: Questionnaire!
    questionnaireResponseHasAnswer: [Answer]!
    questionnaireResponseHasDerivedScoreValue: [ScoreValue]
    questionnaireResponseId: Uriorcurie!
    questionnaireResponseStatus: QuestionnaireResponseStatus!
    questionnaireResponseTimeStamp: Datetime!
    questionnaireResponseLastUpdated: Datetime!
  }

type ScoreDefinition
  {
    scoreDefinitionType: ScoreType!
    scoreDefinitionHasScoreParameter: [ScoreParameter]
    scoreDefinitionUsesQuestion: [Question]!
    scoreDefinitionHasScoreValue: [ScoreValue]
    scoreDefinitionAuthoredByOrg: [Organization]
    scoreDefinitionUsedByQuestionnare: [Questionnaire]
    scoreDefinitionUsedBySection: [Section]
    scoreDefinitionId: Uriorcurie!
    scoreDefinitionLabel: String!
    scoreDefinitionIntervalParams: IntervalParams
    scoreDefinitionFormula: String!
    scoreDefinitionCategories: [String]
    scoreDefinitionInterpretationGuide: String
  }

type ScoreParameter
  {
    scoreParameterPartOfScoreDefinition: ScoreDefinition!
    scoreParameterId: Uriorcurie!
    scoreParameterLabel: String!
    scoreParameterType: ScoreParameterType!
    scoreParameterValueNumerical: ValueNumerical
    scoreParameterValueDateTime: ValueDateTime
  }

type ScoreValue
  {
    scoreDefinitionType: ScoreType!
    scoreValueBasedOnScoreDefinition: ScoreDefinition!
    scoreValueDerivedFromQuestionnaireResponse: [QuestionnaireResponse]!
    scoreValueId: Uriorcurie!
    scoreValueString: ValueString
    scoreValueNumerical: ValueNumerical
    scoreValueTimeStamp: Datetime!
    scoreValueStatus: ScoreValueStatus!
  }

type Section
  {
    sectionHasOrderedQuestion: [OrderedQuestion]
    sectionHasOrderedSection: [OrderedSection]
    sectionInOrderedSection: [OrderedSection]
    sectionUsesScoreDefinition: [ScoreDefinition]
    sectionAuthoredByOrg: [Organization]
    sectionId: Uriorcurie!
    sectionLabel: String!
  }

type ValueCoding
  {
    code: String!
    display: String!
  }

type ValueDateTime
  {
    dateTimeValue: Datetime
  }

type ValueNumerical
  {
    numericalValue: Decimal!
  }

type ValueString
  {
    stringValue: String!
  }

type Vault
  {
    lastUpdated: Datetime!
    hasQuestionnaireResponse: [QuestionnaireResponse]
    vaultManagedByOrg: Organization!
    vaultId: Uriorcurie!
    birthdate: Datetime
    weight: Weight
    fullName: FullName
  }

type Weight
  {
    numericalValue: Decimal!
    weightType: WeightType!
  }

